/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NhacCuaTuiDownloader.java
 *
 * Created on Apr 24, 2011, 4:52:25 PM
 */
package filedownloader;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.htmlparser.NodeFilter;
import org.htmlparser.Parser;
import org.htmlparser.filters.*;
import org.htmlparser.util.NodeList;
import org.htmlparser.util.*;

/**
 *
 * @author haonguyen
 */
public class NhacCuaTuiDownloader extends javax.swing.JFrame {

  /** Creates new form NhacCuaTuiDownloader */
  public NhacCuaTuiDownloader() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    txtTenCaSi = new javax.swing.JTextField();
    btnGo = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    txtLevel1 = new javax.swing.JTextArea();
    jScrollPane3 = new javax.swing.JScrollPane();
    txtRealLink = new javax.swing.JTextArea();
    btnDownLoad = new javax.swing.JButton();
    jScrollPane4 = new javax.swing.JScrollPane();
    txtDownlasableLink = new javax.swing.JTextArea();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtDanhSachBaiHat = new javax.swing.JTextArea();
    txtSoLuong = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setName("Form"); // NOI18N

    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(filedownloader.FileDownloaderApp.class).getContext().getResourceMap(NhacCuaTuiDownloader.class);
    txtTenCaSi.setText(resourceMap.getString("txtTenCaSi.text")); // NOI18N
    txtTenCaSi.setName("txtTenCaSi"); // NOI18N

    btnGo.setText(resourceMap.getString("btnGo.text")); // NOI18N
    btnGo.setName("btnGo"); // NOI18N
    btnGo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGoActionPerformed(evt);
      }
    });

    jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
    jLabel1.setName("jLabel1"); // NOI18N

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
    jPanel1.setName("jPanel1"); // NOI18N

    jScrollPane2.setName("jScrollPane2"); // NOI18N

    txtLevel1.setColumns(20);
    txtLevel1.setRows(5);
    txtLevel1.setName("txtLevel1"); // NOI18N
    jScrollPane2.setViewportView(txtLevel1);

    jScrollPane3.setName("jScrollPane3"); // NOI18N

    txtRealLink.setColumns(20);
    txtRealLink.setRows(5);
    txtRealLink.setName("txtRealLink"); // NOI18N
    jScrollPane3.setViewportView(txtRealLink);

    btnDownLoad.setText(resourceMap.getString("btnDownLoad.text")); // NOI18N
    btnDownLoad.setName("btnDownLoad"); // NOI18N
    btnDownLoad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDownLoadActionPerformed(evt);
      }
    });

    jScrollPane4.setName("jScrollPane4"); // NOI18N

    txtDownlasableLink.setColumns(20);
    txtDownlasableLink.setRows(5);
    txtDownlasableLink.setName("txtDownlasableLink"); // NOI18N
    jScrollPane4.setViewportView(txtDownlasableLink);

    jScrollPane1.setName("jScrollPane1"); // NOI18N

    txtDanhSachBaiHat.setColumns(20);
    txtDanhSachBaiHat.setRows(5);
    txtDanhSachBaiHat.setName("txtDanhSachBaiHat"); // NOI18N
    jScrollPane1.setViewportView(txtDanhSachBaiHat);

    txtSoLuong.setText(resourceMap.getString("txtSoLuong.text")); // NOI18N
    txtSoLuong.setName("txtSoLuong"); // NOI18N

    jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
    jLabel2.setName("jLabel2"); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(40, 40, 40)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(48, 48, 48)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addGap(63, 63, 63)))
        .addComponent(btnDownLoad)
        .addGap(27, 27, 27))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
          .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel2)))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDownLoad)))
            .addContainerGap())))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(118, 118, 118)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtTenCaSi, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(32, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(42, 42, 42)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnGo)
          .addComponent(txtTenCaSi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addGap(56, 56, 56)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  
  private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
    // TODO add your handling code here:
    String tukhoa=txtTenCaSi.getText();
    
    
    String strURL="http://www.nhaccuatui.com/tim_kiem?key="+tukhoa.replaceAll(" ", "+")+"&by=casi"; 
    //String strURL="http://www.nhaccuatui.com/tim_kiem?key=Lam+Truong&by=casi";// @todo: lấy tên riêng
    
    // ko can dung nua
    //NhacCuaTuiClass nct=new NhacCuaTuiClass();
   // ArrayList<StringBuffer> result=nct.layBaiHatTheoCaSi(strURL);
    
     NhacCuaTuiThreadLevel1 level1=new NhacCuaTuiThreadLevel1();
      //level1.text=result.get(i).toString()+"\n";
      level1.url=strURL;
      level1.txtlevel1=this.txtLevel1;
      level1.start();
      
    String []result=txtLevel1.getText().split("\n");
    NhacCuaTuiClass nct=new NhacCuaTuiClass();
    int num=nct.getNumberOfPages(strURL);
    for(int i=0;i<(num-1)*10;i++)// mỗi trang có 10 bài
    {
      //txtLevel1.append(result.get(i).toString()+"\n");
     
      
      
      //------------------------------level 2----------
      
//      String reallink=nct.LayLinkdownLoadCuaBaiHat(result.get(i).toString());      
//      txtRealLink.append(reallink+"\n");
      
      NhacCuaTuiThreadLevel2 level2=new NhacCuaTuiThreadLevel2();
      level2.txtRealLink=this.txtRealLink;
      level2.txtLevel1=this.txtLevel1;
      level2.index=i;
      //level2.url=result[i];
      level2.start();
      //----------level 3----------------------------
      
//      String t=nct.LayLinkThucSuCuaBaiHat(reallink);
//      txtDownlasableLink.append(t+"\n");
      
      NhacCuaTuiThreadlevel3 level3=new NhacCuaTuiThreadlevel3();
      level3.index=i;
      level3.txtDownlasableLink=this.txtDownlasableLink;
      level3.txtRealLink=this.txtRealLink;
      level3.start();
      
      // ----------------level 4-----------------
      
//      String tenbaihat=nct.LayTenBaiHatThongQuanLinkDownloadThucSu(t);
//      txtDanhSachBaiHat.append(tenbaihat+"\n");
      NhacCuaTuiThreadLevel4 level4=new NhacCuaTuiThreadLevel4();
      level4.index=i;
      level4.txtDownlasableLink=this.txtDownlasableLink;
      level4.txtDanhSachBaiHat=this.txtDanhSachBaiHat;
      level4.txtSoLuong=this.txtSoLuong;
      level4.start();

    }
  }//GEN-LAST:event_btnGoActionPerformed

  private void btnDownLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownLoadActionPerformed
    // TODO add your handling code here:
    FileDownloaderView dl=new FileDownloaderView(null);
   
  }//GEN-LAST:event_btnDownLoadActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new NhacCuaTuiDownloader().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnDownLoad;
  private javax.swing.JButton btnGo;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JTextArea txtDanhSachBaiHat;
  private javax.swing.JTextArea txtDownlasableLink;
  private javax.swing.JTextArea txtLevel1;
  private javax.swing.JTextArea txtRealLink;
  private javax.swing.JTextField txtSoLuong;
  private javax.swing.JTextField txtTenCaSi;
  // End of variables declaration//GEN-END:variables
}
